<?php
// Games 76-100
return [
["starlight-shepherd-constellation-puzzler",
"constellation puzzler where a shepherd links stars with a wool-thread telescope",
"shepherd","Woolgather Sky","Baba Is You","Outer Wilds",
"thread lines, star twinkles, cloud wisps, and aurora washes",
"star trial","void moths to outshine","wool-thread linking","restoring the sky","star-embroidered shawl",
"Make long threads link far constellations but snap past the fray bell. Keep short threads snap-safe yet reaching only near stars. Make fraying threads fuzz visibly, then test the same trial threaded long and stitched short.",
"Let outshone moths drop star wool, lenses, and charts on the hill. Make the finds rest where they fall while staying easy to spot and wind up. Test finds threaded long and stitched short without changing the snap and reach rules.",
"sky","star pastures","season","a thread basket and star atlas"],
["beetle-sumo-stable-manager",
"stable manager raising beetle sumo with a grub-diet training ring",
"stablemaster","Kabuto Dohyo","Football Manager","Pokemon",
"shell clacks, dust rings, leaf shadows, and crowd stomps",
"stable bout","rival stables to throw","grub-diet training","taking the kabuto cup","horned beetle crest cap",
"Make protein diets bulk throws heavy but bloat past the sluggish bell. Keep leaf diets nimble yet light to throws. Make bloated beetles drag visibly, then test the same bout fed protein and raised leaf-lean.",
"Let thrown rivals drop grubs, leaves, and tiny belts ringside. Make the prizes rest where they land while staying easy to spot and stable up. Test prizes fed protein and raised leaf-lean without changing the bloat and light rules.",
"dohyo","stable leagues","season","a diet chart and shell polish"],
["glassblower-duelist",
"duelist where a glassblower parries with a gather-and-blow furnace",
"glassblower","Embermouth","Sekiro","Sifu",
"gather glow, blow pipes, annealing shimmer, and furnace roar",
"furnace duel","rival blowers to outshape","gather-and-blow parrying","taking the embermouth","heat-checkered apron",
"Make furnace-hot gathers parry strong but shatter past the chill bell. Keep annealed gathers safe yet soft to edge. Make chilling glass craze visibly, then test the same duel gathered hot and annealed cool.",
"Let outshaped rivals drop pipes, frit, and ribbons by the glory hole. Make the tools rest where they land while staying easy to spot and claim. Test tools gathered hot and annealed cool without changing the shatter and soft rules.",
"works","furnace bays","exhibition","a pipe rack and frit bins"],
["fog-cartographer-horror",
"horror explorer where a cartographer inks fog maps with a bell-echo survey",
"cartographer","Greywater","Amnesia","Outer Wilds",
"fog banks, bell rings, ink bleeds, and lamp cones",
"survey night","fog bells to chart","bell-echo surveying","inking the greywater","fog-damp oilskin coat",
"Make loud bell surveys map far but wake what listens past the answer bell. Keep chalk-mark surveys quiet yet short-ranged. Make answering fog ripple visibly, then test the same night surveyed loud and chalked quiet.",
"Let charted fogs leave bells, charts, and oil on the docks. Make the finds rest where the fog thins while staying easy to spot and log. Test finds surveyed loud and chalked quiet without changing the wake and short rules.",
"water","fog reaches","expedition","a bell set and ink case"],
["arcade-exorcist-rhythm",
"rhythm exorcist where a teen banishes mall ghosts with a dance-pad sigil",
"teen","Neon Food Court","Hi-Fi Rush","Luigis Mansion",
"sigil rings, neon flicker, coin fountains, and bass thumps",
"food-court rite","mall ghosts to banish","dance-pad sigil stepping","closing every rift","arcade-token choker",
"Make full-combo sigils banish fast but trip past the tangle bell on missed steps. Keep simple steps trip-safe yet banishing slowly. Make tangling cords spark visibly, then test the same rite danced full-combo and stepped simple.",
"Let banished ghosts drop tokens, coupons, and lost phones on the tiles. Make the loot skid where it lands while staying easy to spot and feed the arcade. Test loot danced full-combo and stepped simple without changing the trip and slow rules.",
"mall","mall wings","season","a sigil pad and token tin"],
["seed-vault-roguelike",
"seed roguelike where a vaultkeeper plants relic seeds with a season-in-a-bottle greenhouse",
"vaultkeeper","Thousandseed","Hades","Stardew Valley",
"seed bursts, bottle seasons, soil crumbs, and sun shafts",
"vault run","blight shades to weed out","bottle-season planting","filling the thousandseed","seed-packet bandolier",
"Make summer bottles fruit fast but parch past the wilt bell. Keep spring bottles wilt-safe yet fruiting slowly. Make wilting leaves crisp visibly, then test the same run bottled summer and bottled spring.",
"Let weeded shades drop seeds, labels, and trowels in the rows. Make the finds rest where they fall while staying easy to spot and vault. Test finds bottled summer and bottled spring without changing the parch and slow rules.",
"vault","vault wings","growing year","a seed index and bottle shelf"],
["harbor-tugboat-puzzler",
"harbor puzzler where a tug captain nudges ships with a rope-and-tide grid",
"captain","Tugwater","Baba Is You","Mini Metro",
"rope arcs, tide lines, gull cries, and buoy bells",
"harbor morning","stuck freighters to nudge free","rope-and-tide nudging","clearing the harbor","salt-white captain cap",
"Make high-tide nudges float ships free but surge past the snap bell. Keep low-tide nudges snap-safe yet grinding on mud. Make grinding hulls groan visibly, then test the same morning pushed high and worked low.",
"Let freed freighters drop crates, ropes, and manifests on the quay. Make the cargo rest where cranes set it while staying easy to spot and log. Test cargo pushed high and worked low without changing the surge and grind rules.",
"harbor","harbor berths","shipping year","a knot board and tide table"],
["mirror-plague-doctor",
"plague-doctor adventure curing mirror-coughed towns with a leech-and-lantern kit",
"doctor","Vetromir","Pathologic","Gris",
"mirror coughs, leech squirms, lantern moths, and bell tolls",
"ward round","mirror coughs to cure","leech-and-lantern curing","lifting the plague","beaked mask with cracked lens",
"Make lantern cures cleanse wards fast but crack mirrors past the shard bell. Keep leech cures shard-safe yet slow to a crawl. Make cracking mirrors spider visibly, then test the same round lantered bright and leeched slow.",
"Let cured wards leave masks, herbs, and thanks on the stoop. Make the gifts rest where left while staying easy to spot and gather. Test gifts lantered bright and leeched slow without changing the crack and slow rules.",
"town","quarantine wards","plague year","a cure ledger and lantern oils"],
["satellite-gardener-puzzler",
"orbital puzzler where a gardener aims sunlight with a mirror-bloom array",
"gardener","Petal Array","Portal","Dorfromantik",
"mirror glints, petal drift, orbit lines, and sunrise sweeps",
"bloom pass","shade blights to burn off","mirror-bloom aiming","blooming the array","zero-g pruning shears",
"Make focused mirrors bloom beds fast but scorch past the crisp bell. Keep diffused mirrors scorch-safe yet blooming slowly. Make crisping petals brown visibly, then test the same pass focused tight and diffused wide.",
"Let bloomed beds drop petals, seeds, and lenses along the truss. Make the finds drift where they fall while staying easy to spot and net. Test finds focused tight and diffused wide without changing the scorch and slow rules.",
"array","array rings","growing orbit","a bloom chart and mirror keys"],
["deep-trench-post-office",
"deep-sea adventure where a postal crab sorts abyssal mail with a pressure-seal sorter",
"crab","Hadal Post","Papers Please","Subnautica",
"pressure gauges, ink clouds, lanternfish swarms, and vent steam",
"mail dive","lost letters to deliver","pressure-seal sorting","delivering every letter","brass postal badge",
"Make express seals deliver fast but burst past the crush bell. Keep standard seals crush-safe yet slow through the trench. Make bursting envelopes bulge visibly, then test the same dive sealed express and stamped standard.",
"Let delivered letters earn stamps, pearls, and thanks in the slots. Make the rewards rest where left while staying easy to spot and file. Test rewards sealed express and stamped standard without changing the burst and slow rules.",
"trench","post routes","mail year","a stamp book and seal press"],
["clockmaker-mouse-platformer",
"tiny platformer where a mouse clockmaker winds gears with a key-backpack spring",
"clockmaker","Ticktock Walls","Celeste","Hollow Knight",
"gear teeth, spring coils, dust in sun shafts, and chime puffs",
"wall ascent","dust mites to wind past","key-backpack winding","topping the ticktock","key-backpack with brass key",
"Make overwound springs leap high but snap past the strain bell. Keep gentle winds snap-safe yet hopping low. Make straining coils whine visibly, then test the same ascent overwound and gently wound.",
"Let wound gears drop teeth, oil, and crumbs on the ledges. Make the bits rest where they land while staying easy to spot and pocket. Test bits overwound and gently wound without changing the snap and low rules.",
"house","wall tiers","season","a gear box and oil pen"],
["storm-lighthouse-rts",
"coastal RTS where a warden chains lighthouse beams with a storm-charge grid",
"warden","Greywidow Chain","They Are Billions","Frostpunk",
"beam sweeps, storm arcs, wave crash, and gull alarms",
"storm defense","drowned hulls to burn back","lighthouse-beam chaining","holding the chain","storm-grey warden coat",
"Make chained beams burn hulls fast but brown out past the surge bell. Keep lone beams surge-safe yet burning slowly. Make surging lamps flicker visibly, then test the same defense chained wide and lit lone.",
"Let burned hulls spill timbers, oil, and bells on the rocks. Make the wreck rest where waves leave it while staying easy to spot and haul. Test wreck chained wide and lit lone without changing the brownout and slow rules.",
"coast","lighthouse reaches","storm year","a beam chart and oil reserve"],
["paper-tax-office-rpg",
"paperwork RPG where a clerk stamps dungeon permits with a stamp-combo desk",
"clerk","The Rubber-Stamp Depths","Papers Please","Disco Elysium",
"stamp thumps, paper stacks, ink pads, and desk-lamp pools",
"permit day","impostor delves to deny","stamp-combo filing","balancing the books","oversized approval stamp",
"Make combo stamps clear queues fast but smudge past the blot bell. Keep single stamps blot-safe yet crawling slowly. Make smudging forms bleed visibly, then test the same day stamped combo and stamped single.",
"Let cleared delves drop forms, seals, and bribes on the desk. Make the papers stack where left while staying easy to read and file. Test papers stamped combo and stamped single without changing the smudge and slow rules.",
"office","permit windows","fiscal year","a stamp wall and ledger"],
["vending-machine-dungeon-roguelike",
"vending roguelike where a restocker fights snack mimics with a coin-and-coil arsenal",
"restocker","Humvault 24","Hades","Balatro",
"coil spins, coin glints, wrapper bursts, and fluorescent hum",
"restock run","snack mimics to vend-slay","coin-and-coil combat","stocking every row","coin-changer belt",
"Make jackpot coils vend jackpots but jam past the tilt bell. Keep exact-change coils jam-safe yet paying plainly. Make tilting machines rock visibly, then test the same run jackpot-fed and exact-changed.",
"Let vended mimics drop snacks, coins, and prize cards in the tray. Make the drops thud where they land while staying easy to spot and shelve. Test drops jackpot-fed and exact-changed without changing the jam and plain rules.",
"vault","vending rows","stock year","a coin ledger and coil keys"],
["moss-train-conductor-sim",
"rail sim where a conductor grows station gardens with a timetable-and-trowel loop",
"conductor","Mossline","Stardew Valley","Mini Metro",
"petal drift, timetable chimes, steam curls, and platform lanterns",
"garden loop","weeds and delays to prune","timetable-and-trowel looping","blooming the mossline","ivy-trimmed conductor cap",
"Make express loops bloom towns fast but skip stops past the complaint bell. Keep all-stop loops complaint-free yet blooming slowly. Make skipping boards flash visibly, then test the same loop run express and all-stop.",
"Let bloomed towns leave seeds, tickets, and pies on the platform. Make the gifts rest where left while staying easy to spot and load. Test gifts run express and all-stop without changing the skip and slow rules.",
"line","garden stations","timetable year","a trowel roll and timetable"],
["deep-space-noodle-bar",
"zero-g bar sim where a chef tosses noodles with a broth-orbit ladle",
"chef","Broth Orbit","Overcooked","Outer Wilds",
"noodle arcs, broth globes, steam curls, and neon menus",
"dinner rush","impatient spacers to satisfy","broth-orbit tossing","earning five ladles","noodle-net hair scarf",
"Make orbit tosses plate fast but splatter past the spill bell. Keep ladled plates spill-safe yet plating slowly. Make splattering broth bead visibly, then test the same rush tossed orbital and ladled careful.",
"Let satisfied spacers leave credits, chopsticks, and reviews on the trays. Make the tips float where left while staying easy to spot and pocket. Test tips tossed orbital and ladled careful without changing the splatter and slow rules.",
"station","bar decks","season","a ladle set and broth chart"],
["ghost-radio-dj-horror",
"horror where a night DJ tunes ghost frequencies with a fader-and-antenna booth",
"dj","Static Bloom","Phasmophobia","Alan Wake",
"fader static, antenna hum, neon dial glow, and dead-air chills",
"night broadcast","dead-air wraiths to tune out","fader-and-antenna tuning","holding the frequency","headphone with taped mic",
"Make boost-gain tunes reach far ghosts but feedback past the shriek bell. Keep low-gain tunes shriek-safe yet reaching only near static. Make feedback needles slam visibly, then test the same broadcast boosted and kept low.",
"Let tuned ghosts leave requests, tapes, and dedications in the booth. Make the notes rest where slipped while staying easy to read and play. Test notes boosted and kept low without changing the feedback and near rules.",
"station","night frequencies","season","a request log and antenna map"],
["spire-chimney-sweep-platformer",
"vertical platformer where a sweep climbs living chimneys with a brush-and-draft kit",
"sweep","Sootspire","Celeste","Hollow Knight",
"soot puffs, draft lines, ember sparks, and wind howls",
"spire climb","soot shades to sweep","brush-and-draft climbing","topping the sootspire","soot-blackened top hat",
"Make strong drafts lift fast but choke past the cough bell. Keep still shafts cough-safe yet climbing slowly. Make choking throats heave visibly, then test the same climb drafted strong and climbed still.",
"Let swept shades drop brushes, coins, and lucky buttons on the ledges. Make the finds rest where they land while staying easy to spot and pocket. Test finds drafted strong and climbed still without changing the choke and slow rules.",
"spire","spire flues","sweep year","a brush roll and draft chart"],
["coral-court-lawyer-sim",
"courtroom sim where a crab lawyer argues reef cases with an evidence-bubble brief",
"lawyer","The Brine Bench","Ace Attorney","Papers Please",
"bubble exhibits, gavel knocks, current sways, and plankton motes",
"trial day","guilty verdicts to overturn","evidence-bubble arguing","winning every case","barnacled barrister wig",
"Make surprise bubbles sway juries fast but burst past the mistrial bell. Keep filed bubbles safe yet swaying slowly. Make bursting exhibits pop visibly, then test the same day argued splashy and filed careful.",
"Let won cases leave pearls, writs, and thanks on the bench. Make the rewards rest where set while staying easy to spot and file. Test rewards argued splashy and filed careful without changing the burst and slow rules.",
"reef","court tiers","session","a bubble brief and precedent shelf"],
["sunken-library-diver",
"diving adventure where a diver reshelves drowned books with a current-and-lantern rig",
"diver","The Drowned Stacks","Subnautica","Abzu",
"current ribbons, page flutters, lantern halos, and silt blooms",
"shelf dive","ink squids to reshelve past","current-and-lantern diving","restoring the stacks","brass diving helmet",
"Make strong currents shelve fast but scatter pages past the drift bell. Keep still water scatter-safe yet shelving slowly. Make drifting pages spiral visibly, then test the same dive ridden strong and finned still.",
"Let shelved squids drop quills, clasps, and bookmarks on the shelves. Make the finds rest where the current leaves them while staying easy to spot and shelve. Test finds ridden strong and finned still without changing the scatter and slow rules.",
"stacks","drowned wings","expedition","a catalog and lantern oils"],
["avalanche-shepherd-rescue",
"mountain rescue where a shepherd digs slab slides with a bell-and-probe line",
"rescuer","White Shepherd Col","Steep","Celeste",
"slab cracks, probe pings, bell echoes, and powder plumes",
"rescue day","buried bells to dig out","bell-and-probe searching","clearing the col","avalanche-transceiver vest",
"Make loud bell sweeps find deep bells but trigger slabs past the fracture bell. Keep probe-only searches slab-safe yet finding slowly. Make fracturing snow boom visibly, then test the same day swept loud and probed quiet.",
"Let dug-out caches yield bells, ropes, and cocoa on the snow. Make the finds rest where dug while staying easy to spot and sled out. Test finds swept loud and probed quiet without changing the trigger and slow rules.",
"col","rescue faces","season","a probe set and rescue log"],
["antique-robot-tea-shop",
"shop sim where a robot serves memory-tea with a steep-and-polish counter",
"robot","The Copper Kettle","Stardew Valley","VA-11 Hall-A",
"steam curls, polish shine, gear ticks, and rain on glass",
"tea shift","lonely regulars to warm","steep-and-polish serving","earning five kettles","cracked porcelain faceplate",
"Make memory blends warm hearts fast but glitch past the static bell. Keep house blends glitch-safe yet warming slowly. Make glitching optics fizz visibly, then test the same shift poured memory and house-steady.",
"Let warmed regulars leave stories, gears, and tips on the counter. Make the keepsakes rest where left while staying easy to read and keep. Test keepsakes poured memory and house-steady without changing the glitch and slow rules.",
"street","tea rooms","year","a blend book and polish kit"],
["tide-lock-keeper-puzzler",
"canal puzzler where a keeper floods locks with a gate-and-gull timetable",
"keeper","Gullgate","Baba Is You","Mini Metro",
"gate groans, water levels, gull cries, and rope coils",
"lock day","stranded barges to float","gate-and-gull timing","clearing the gullgate","tarred keeper coat",
"Make double-gate floods lift fast but swamp past the spill bell. Keep single-gate floods spill-safe yet lifting slowly. Make swamping decks wash visibly, then test the same day flooded double and gated single.",
"Let floated barges pay tolls, eels, and letters at the gate. Make the payments rest where handed while staying easy to spot and ledger. Test payments flooded double and gated single without changing the swamp and slow rules.",
"canal","lock reaches","shipping year","a gate key ring and tide table"],
["moth-keeper-lamp-sim",
"night sim where a keeper tends lighthouse moths with a dim-and-amber lamp",
"keeper","Amberwatch","Viva Pinata","Hollow Knight",
"wing dust, lamp halos, night blooms, and foghorn moans",
"moth night","lamp-crazed swarms to settle","dim-and-amber tending","raising the amberwatch","moth-wing cloak",
"Make bright lamps draw rare moths but frenzy swarms past the flutter bell. Keep amber-dim lamps frenzy-safe yet drawing slowly. Make frenzied wings blur visibly, then test the same night lamped bright and kept amber-dim.",
"Let settled swarms leave scales, cocoons, and maps on the sill. Make the gifts rest where they land while staying easy to spot and jar. Test gifts lamped bright and kept amber-dim without changing the frenzy and slow rules.",
"watch","lamp tiers","season","a cocoon shelf and lamp oils"],
["bone-market-tycoon",
"market tycoon where a trader prices relics with a haggle-and-appraise stall",
"trader","The Marrow Market","Recettear","Papers Please",
"coin clinks, appraise glints, crowd haggles, and canvas flaps",
"market day","rival stalls to outsell","haggle-and-appraise pricing","cornering the marrow","abacus with skull beads",
"Make bold haggles sell high but insult past the walkout bell. Keep fair prices walkout-safe yet earning thinly. Make insulted buyers storm visibly, then test the same day haggled bold and priced fair.",
"Let outsold rivals leave stock, coins, and rumors at the stall. Make the leavings rest where dropped while staying easy to spot and shelf. Test leavings haggled bold and priced fair without changing the insult and thin rules.",
"market","market rows","season","a price ledger and appraise lens"],
];
