<?php
// Games 26-50
return [
["zero-g-salvage-engineer",
"zero-g salvage sim where an engineer cuts wrecks with a tethered plasma torch and a debris-drift engine",
"engineer","Rust Halo","Hardspace: Shipbreaker","Outer Wilds",
"plasma cutter glare, tumbling hull shards, leaking coolant crystals, and helmet-lamp cones",
"salvage run","rival scrappers to outcut","debris-drift tethering","stripping wrecks clean","mag-strip tool belt",
"Make severed fuel cells vent and push nearby debris along their jet cone. Keep anchored keel beams fixed so cuts around them stay predictable. Make venting cells frost over visibly, then test the same cut beside a venting cell and on a keel beam.",
"Let drifting scrap, canisters, and tools ride the existing drift field into the collector net. Make the objects tumble with real spin while staying easy to identify and grab. Test pulls near a venting cell and near a keel beam without changing the venting and anchor rules.",
"debris field","wreck sectors","contract chain","a scrap catalog and torch rig"],
["vampire-vineyard-keeper",
"gothic management sim where a vampire vintner balances blood moon vintages against hunter patrols",
"vintner","Crimson Terraces","Stardew Valley","Papers Please",
"blood-moon glow, mist over rows, lantern moths, and fermenting barrel bubbles",
"harvest night","hunter patrols to evade","moon-phase vintage tuning","bottling grand vintages","high-collared black cape",
"Make blood-moon rows ripen grapes twice as fast but attract hunters to lit rows. Keep chapel-shadowed rows slow yet hidden from patrols. Make ripe rows glisten red, then test the same harvest under blood moon and in chapel shadow.",
"Let wind scatter cuttings, corks, and dropped vials across the terraces. Make the items roll on the existing slope physics while staying easy to spot and collect. Test spills under blood moon and in chapel shadow without changing the ripening and hiding rules.",
"vineyard","vineyard slopes","vintage years","a cellar ledger and vintage press"],
["subway-ghost-conductor",
"first-person horror where a night conductor guides a ghost train with a lantern-signal system",
"conductor","Last Line","P.T.","Outer Wilds",
"flickering fluorescents, breath fog, tunnel wind, and signal-lamp pools",
"night shift","platform wraiths to calm","lantern-signal routing","delivering lost souls","brass ticket puncher",
"Make lit carriages calm wraiths but drain the lantern oil while bright. Keep dark carriages oil-safe yet restless and cold. Make calm wraiths settle into seats, then test the same stop with lamps high and shuttered.",
"Let forgotten tickets, umbrellas, and lunchboxes slide when the train brakes. Make the items obey the existing carriage physics while staying easy to spot and return. Test items with lamps high and shuttered without changing the calm and oil rules.",
"line","haunted stations","night loop","a lost-property log and signal kit"],
["desert-sail-racer",
"wind-physics racer where a sail jockey drifts sand skiffs across dune seas",
"jockey","Glassdune Sea","Forza Horizon","Sonic Racing",
"sail snap, sand spray, heat shimmer, and mirage glints",
"time trial","rival jockeys to outdrift","sail-trim boosting","winning trials","sand-scarred helmet visor",
"Make tailwind legs overcharge the boost sail but overheat it past the red band. Keep luffing headwind legs cool yet slow unless tacked. Make overheating sails glow at the seams, then test the same leg downwind and tacked upwind.",
"Let wrecked rivals drop sails, rivets, and water skins onto the course. Make the drops skid on the existing dune physics while staying easy to spot and grab. Test drops on a tailwind leg and a tacked leg without changing the boost and cooling rules.",
"erg","race regions","grand tour","a sail loft and rig tuning"],
["ink-detective-visual-novel",
"noir visual novel where an ink detective rewinds testimony with a blot-and-thread board",
"detective","Rainblot Row","Disco Elysium","Danganronpa",
"ink blots, rain on glass, neon through blinds, and cigarette curls",
"interrogation","lying suspects to corner","testimony-thread rewinding","closing the case","ink-stained trench coat",
"Make pressed suspects contradict themselves if shown two linked clues in one thread. Keep unlinked clue dumps safe but ignored by the suspect. Make cracking lies flicker on screen, then test the same suspect with a linked thread and a random dump.",
"Let solved witnesses leave letters, keys, and photos on the board. Make the keepsakes pin neatly while staying easy to read and revisit. Test keepsakes from linked threads and random dumps without changing the link and ignore rules.",
"precinct","case files","season of cases","an evidence board and ink kit"],
["mycelium-city-builder",
"cozy city builder growing districts on a living mycelium mat with spore-wind spread",
"mayor","Sporefall","Cities: Skylines","Dorfromantik",
"spore drift, cap-roof bounce, mycelium glow veins, and rain patter",
"founding season","blight pockets to clear","spore-wind district spread","raising a spore capital","moss-green mayoral sash",
"Make linked mycelium roads share nutrients and double growth on the web. Keep paved stone roads unlinked so districts on them grow alone. Make linked roads pulse softly, then test the same district on mycelium and on stone.",
"Let harvest drones drop spores, timber, and lost tools along the roads. Make the drops settle where the wind leaves them while staying easy to spot and collect. Test drops on mycelium and on stone without changing the link and pavement rules.",
"colony","city tiers","charter ages","a spore atlas and civic works"],
["clockwork-tower-defense",
"clockwork tower defense where a horologist gears towers with a mainspring-tension grid",
"horologist","Brass Bastion","Defense Grid","Into the Breach",
"gear mesh, mainspring glow, oil mist, and chime shockwaves",
"siege night","rust mites to grind down","mainspring-tension routing","holding the bastion","gear-monocle",
"Make overwound towers fire double but jam smoking past the red tick. Keep rested springs safe yet firing at half rate. Make straining gears shriek and spark, then test the same wave overwound and fully rested.",
"Let smashed mites drop springs, cogs, and oil cans on the lanes. Make the drops rattle to rest while staying easy to spot and salvage. Test drops from overwound kills and rested kills without changing the overwind and rest rules.",
"bastion","bastion rings","siege calendar","a gear workshop and tower registry"],
["algae-factory-automation",
"factory automation sim refining algae vats with a flow-pressure pipe network",
"technician","Greenline Works","Factorio","Satisfactory",
"vat bubbles, pipe pressure glow, steam vents, and drifting spores",
"first shift","clog blooms to flush","flow-pressure pipe routing","hitting quota","acid-green gloves",
"Make high-pressure lines refine twice as fast but burst past the red valve. Keep low-pressure loops safe yet slow to a trickle. Make straining pipes sweat and hiss, then test the same line run hot and throttled low.",
"Let burst pipes spit algae cakes, bolts, and filters onto the floor. Make the debris scatter on the existing floor physics while staying easy to spot and sweep. Test debris from hot lines and low lines without changing the burst and trickle rules.",
"works","factory halls","production quotas","a pipe catalog and valve kit"],
["lunar-farming-colony",
"low-gravity farming colony where a botanist cycles domes through day-night shutters",
"botanist","Mare Tranquil Farm","Stardew Valley","Surviving Mars",
"regolith dust, dome condensation, shutter light blades, and floating seeds",
"first harvest","dust mites to sieve out","shutter-cycle crop tuning","bringing in harvests","patched pressure-suit scarf",
"Make long-day cycles fruit crops fast but scorch them past the heat bell. Keep shuttered night cycles safe for water yet stalling fruit. Make scorching leaves curl visibly, then test the same bed on long-day and shuttered night.",
"Let rover treads kick up seeds, tools, and ice chips across the domes. Make the items bounce in low gravity while staying easy to spot and retrieve. Test spills on long-day and shuttered night without changing the scorch and stall rules.",
"colony","colony domes","settlement years","a seed vault and shutter board"],
["kraken-fishing-roguelike",
"roguelike fishing battler where an angler duels krakens with a tension-line harpoon",
"angler","Blacktide Grounds","Dredge","Hades",
"line tension arcs, spray bursts, bioluminescent lures, and deck lantern sway",
"deep cast","kraken arms to sever","tension-line dueling","landing the catch","oilskin yellow coat",
"Make taut lines deal double haul damage but snap past the red gauge. Keep slack lines safe yet unable to wound. Make straining lines sing and fray, then test the same duel hauled taut and left slack.",
"Let severed arms drop suckers, ink sacs, and tackle overboard. Make the drops bob on the existing waves while staying easy to spot and gaff. Test drops from taut duels and slack duels without changing the snap and slack rules.",
"grounds","fishing grounds","season","a tackle box and harpoon rack"],
["paper-plane-racing-league",
"toy-box racer where a kid folds paper planes with a thermal-lift playground",
"kid pilot","Gymnasium Thermals","Mario Kart","Fall Guys",
"paper flutter, chalk dust, sunbeam columns, and curtain sway",
"playground grand prix","rival folders to outglide","thermal-lift gliding","winning the grand prix","red paper-crown visor",
"Make sunbeam thermals lift planes high but wobble folds past the flutter limit. Keep shaded air stable yet sinking slowly. Make wobbling wings crinkle audibly, then test the same glide inside a thermal and through shade.",
"Let crashed rivals drop stickers, clips, and spare folds on the course. Make the drops flutter down while staying easy to spot and grab. Test drops inside thermals and in shade without changing the lift and sink rules.",
"school","playground circuits","season","a fold book and sticker wall"],
["yokai-bathhouse-keeper",
"cozy sim where a keeper soothes yokai with a mineral-spring mixing system",
"keeper","Steamveil Baths","Spirited Away","Stardew Valley",
"steam curls, mineral shimmer, lantern reflections, and dripping eaves",
"opening night","grumbly yokai to soothe","spring-mixing bath tuning","earning five-star soaks","cedar ladle headband",
"Make sulfur springs soothe rock yokai fast but itch river spirits until rinsed. Keep moonwell water gentle for all yet slow to satisfy. Make itchy spirits scratch visibly, then test the same guest in sulfur and in moonwell.",
"Let guests drop charms, coins, and forgotten towels by the pools. Make the items steam where they land while staying easy to spot and return. Test drops at sulfur pools and moonwell pools without changing the soothe and itch rules.",
"baths","bath wings","festival year","a mineral chart and guest book"],
["sandworm-bounty-rider",
"open-desert action where a bounty rider harpoons sandworms with a thumper-rhythm lure",
"rider","Howling Erg","Shadow of the Colossus","Monster Hunter",
"sand plumes, thumper rings, scale glints, and heat haze",
"worm hunt","sandworms to harpoon","thumper-rhythm luring","claiming bounties","worm-tooth pauldron",
"Make thumper beats synced to the worm's pulse enrage it into surfacing. Keep arrhythmic beats safe but ignored under the sand. Make surfacing sand dome visibly, then test the same lure synced and arrhythmic.",
"Let felled worms spill teeth, glands, and saddle gear across the dunes. Make the spills half-bury where they land while staying easy to spot and dig out. Test spills from synced hunts and arrhythmic hunts without changing the surface and ignore rules.",
"erg","hunting grounds","bounty board","a trophy wall and thumper kit"],
["drone-swarm-rts",
"micro RTS where a handler commands a drone swarm with a signal-relay mesh",
"handler","Ash Relay","StarCraft","Into the Breach",
"relay beams, rotor wash, signal static, and dust kicked sideways",
"relay defense","rogue swarms to jam","signal-relay mesh routing","holding the relay","signal-orange handler vest",
"Make chained relay tiles boost drone speed across the whole mesh. Keep dead-zone rock unlinked so drones there crawl alone. Make linked tiles hum softly, then test the same push from relay mesh and from dead zone.",
"Let downed drones drop cells, rotors, and chips on the field. Make the drops scatter on the existing blast physics while staying easy to spot and salvage. Test drops on relay mesh and dead zone without changing the boost and crawl rules.",
"basin","relay sectors","campaign","a hangar roster and relay map"],
["frog-pond-fishing-sim",
"tranquil fishing sim where a pondkeeper reads ripples with a fly-tying bench",
"pondkeeper","Lilybell Pond","Stardew Valley","Animal Crossing",
"ripple rings, dragonfly zips, lily sway, and morning mist",
"dawn cast","old pond kings to land","ripple-reading casts","completing the creel","woven lily hat",
"Make dawn-mist casts reveal lunkers but tangle line in lily stems. Keep noon-clear casts safe from tangles yet spooking shallows. Make tangled stems shake visibly, then test the same cast at dawn mist and high noon.",
"Let breezes push loose flies, bobbers, and lunch tins across the dock. Make the items drift on the existing ripple field while staying easy to spot and retrieve. Test drift at dawn mist and high noon without changing the tangle and spook rules.",
"pond","pond coves","fishing year","a fly book and creel log"],
["neon-taxi-driver",
"night driving sim where a cabbie chains fares with a rain-slick drift meter",
"cabbie","Neon Mile","Crazy Taxi","Need for Speed",
"neon reflections, rain streaks, fare pings, and wiper arcs",
"night shift","rival cabs to outfare","drift-meter fare chaining","topping the leaderboard","checkered cab cap",
"Make rain-slick avenues boost drift fares but hydroplane past the grip warning. Keep parking-garage decks grippy yet fareless and slow. Make sliding tires smoke blue, then test the same run on rain avenues and in a dry garage.",
"Let rushed fares drop phones, umbrellas, and tips at the curb. Make the items glint under neon while staying easy to spot and return. Test drops on rain avenues and in dry garages without changing the drift and grip rules.",
"mile","city wards","meter year","a garage and fare atlas"],
["skeleton-crew-pirate-roguelike",
"naval roguelike where a skeleton captain trades cursed doubloons for tide favors",
"captain","Grinning Tide","FTL","Hades",
"cannon smoke, tide foam, lantern ghosts, and sail rip",
"broadside run","hunter frigates to sink","tide-favor bartering","breaking the curse","barnacled tricorn",
"Make cursed doubloons empower broadsides but mark the ship on every hunter chart. Keep spent-tide favors quiet yet weak to hull damage. Make marked hulls glow in fog, then test the same broadside cursed-rich and tide-quiet.",
"Let sunk frigates spill charts, powder, and figureheads into the swell. Make the wreckage bob on the existing waves while staying easy to spot and haul. Test wreckage cursed-rich and tide-quiet without changing the mark and quiet rules.",
"archipelago","cursed waters","voyage","a curse ledger and gun deck"],
["origami-mech-duelist",
"arena duelist where a folder pilots a paper mech with crease-heat swordplay",
"folder","Thousandfold Ring","Armored Core","Sekiro",
"paper creases, fold steam, ink slashes, and confetti bursts",
"fold duel","rival folders to outfold","crease-heat blade dueling","taking the ring","crane-fold helm crest",
"Make heated creases cut deep but burn through folds past the scorch tick. Keep cool folds safe yet dealing half damage. Make scorching seams smoke at the edge, then test the same duel run hot and fully cooled.",
"Let unmade rivals shed folds, seals, and ink sticks on the ring. Make the drops flutter down while staying easy to spot and claim. Test drops from hot duels and cooled duels without changing the burn and half-damage rules.",
"ring","duel rings","tournament","a fold archive and ink seals"],
["cactus-cowboy-duelist",
"western duelist where a cactus cowboy draws with a sun-heat standoff meter",
"cowboy","Prickly Noon","Red Dead Redemption","Sifu",
"dust devils, heat shimmer, spur jingles, and tumbleweed rolls",
"high-noon standoff","rival outlaws to outdraw","sun-heat draw timing","cleaning up the town","cactus-flower hat band",
"Make high-sun draws fire fastest but blind past the glare bell. Keep shaded draws safe from glare yet a beat slower. Make glaring sights wash white, then test the same draw at high noon and from the shade.",
"Let beaten outlaws drop bounties, spurs, and wanted posters in the dust. Make the drops kick up where they fall while staying easy to spot and claim. Test drops at high noon and from shade without changing the glare and shade rules.",
"frontier","frontier towns","posse season","a bounty board and iron kit"],
["aurora-research-station-survival",
"arctic survival where a researcher routes generator heat through aurora storms",
"researcher","Whiteout Point","The Long Dark","Frostpunk",
"aurora ribbons, breath fog, generator glow, and snow scour",
"storm night","frostbite shades to outlast","generator-heat routing","surviving the season","fur-trimmed parka hood",
"Make aurora storms charge batteries fast but scramble sensors while the sky burns. Keep whiteout calm safe for sensors yet freezing twice as fast. Make scrambled screens fizz green, then test the same night under aurora and in whiteout.",
"Let supply drops scatter batteries, cocoa, and fuses across the drifts. Make the crates half-bury where they land while staying easy to spot and dig out. Test drops under aurora and in whiteout without changing the charge and freeze rules.",
"station","research outposts","expedition","a lab bench and heat map"],
["candy-golem-match3-battler",
"match-3 battler where a chocolatier hurls candy golems with a sugar-rush combo oven",
"chocolatier","Gumdrop Works","Puzzle Quest","Tetris Effect",
"candy shatter, sugar glow, wrapper flutters, and oven warmth",
"sugar bout","sour golems to melt","sugar-rush match chaining","winning the bake-off","peppermint-striped apron",
"Make long sugar chains detonate bonus golems but rot teeth past the ache bell. Keep small matches safe yet dealing chip damage. Make aching boards throb red, then test the same board chained long and matched small.",
"Let melted golems drop gummies, wrappers, and recipe cards on the tray. Make the drops bounce softly while staying easy to spot and sweep. Test drops from long chains and small matches without changing the detonate and chip rules.",
"works","candy wards","bake-off","a recipe tin and oven dials"],
["lighthouse-horror-keeper",
"first-person horror where a keeper sweeps a light beam to hold back drowned things",
"keeper","Greywidow Light","Amnesia","Outer Wilds",
"beam sweep, foghorn rings, brine drips, and gull cries",
"storm watch","drowned things to hold back","light-sweep warding","keeping the light","oilskin keeper coat",
"Make focused beams burn back the drowned but overheat the lamp past the crack tick. Keep shuttered dark safe for the lamp yet letting things climb. Make cracking glass spider visibly, then test the same watch beamed wide and shuttered.",
"Let the tide leave shells, letters, and brass keys on the rocks. Make the gifts glint in the existing beam while staying easy to spot and gather. Test gifts under full beam and shuttered dark without changing the burn and climb rules.",
"coast","watch nights","keeper years","a logbook and lamp kit"],
["sumo-frog-wrestler",
"physics sports battler where a frog wrestler grips the mud ring with a splash-stomp meter",
"wrestler","Mudmoon Dohyo","Gang Beasts","Wii Sports",
"mud splats, splash rings, belly drums, and firefly swarms",
"mud bout","rival frogs to ring-out","splash-stomp gripping","taking the basho","lotus-leaf mawashi",
"Make wet mud grip throws strong but slide past the slick bell. Keep dry clay safe to stand yet weak to throws. Make slick mud shine at the rim, then test the same bout fought wet and fully dry.",
"Let rung-out rivals drop charms, sandals, and rice cakes ringside. Make the drops splat into the mud while staying easy to spot and retrieve. Test drops from wet bouts and dry bouts without changing the grip and slide rules.",
"marsh","tournament marshes","basho","a stable diet chart and grip salts"],
["time-capsule-archaeologist",
"dusty adventure where an archaeologist decodes strata with a brush-and-sonar kit",
"archaeologist","Strata of Echoes","Tomb Raider","Outer Wilds",
"dust motes, brush strokes, sonar pings, and sun shafts in shafts",
"dig day","tomb shades to rebury","strata-sonar decoding","sealing the strata","dust-caked fedora",
"Make sonar pings reveal relics deep but wake shades in the same stratum. Keep hand-brush digs quiet yet slow to a crawl. Make waking dust swirl black, then test the same dig pinged loud and brushed quiet.",
"Let settled dust drop shards, beads, and field notes across the trench. Make the finds glint where they land while staying easy to spot and bag. Test finds from loud pings and quiet brushes without changing the reveal and wake rules.",
"site","dig strata","expedition","a finds tray and sonar rig"],
["cloud-whale-sky-safari",
"serene safari where a spotter catalogs cloud whales with a song-echo tracker",
"spotter","Blue Drift","Abzu","Pokemon Snap",
"whale song rings, cloud foam, sun dogs, and feather drift",
"safari drift","sky poachers to photograph down","song-echo tracking","completing the catalog","whale-song brass horn",
"Make echo songs reveal whales far but startle calves into diving. Keep silent drifts calf-safe yet blind past the near clouds. Make diving wakes bloom white, then test the same drift sung loud and fully silent.",
"Let passing whales shed baleen, feathers, and lost cameras along the drift. Make the drift carry them gently while staying easy to spot and net. Test drift sung loud and fully silent without changing the reveal and startle rules.",
"drift","sky regions","migration","a catalog and echo horn"],
];
