<?php
// Games 1-25: action/adventure, RPG/roguelike, sim (part 1)
// Fields: slug, core, hero, concept, atmo, sys, visuals, encounter,
//         targets, system, reward_action, identity, rule1, rule2,
//         world, themes, progression, meta
return [
["top-down-pixel-dungeon-crawler",
"top-down pixel dungeon crawler with real-time combat and a procedural fluid engine",
"adventurer","Tideglass Caverns","Animal Well","Caves of Qud",
"reactive water, blood particles, metal sparks, and responsive lighting",
"combat encounter","enemies to fight","dynamic fluid","defeating enemies","red cape",
"Make electrical attacks propagate through connected water and damage creatures in the charged area. Keep stone surfaces safe from water-borne electricity. Make the charged water readable, then test the same attack with the player standing in water and on stone.",
"Let water currents move physical loot and environmental debris. Make the objects respond to the existing fluid simulation while remaining easy to identify and collect. Test drops in flowing water and on dry ground without changing the electricity and safe-stone rules.",
"dungeon","floor themes","descent","an inventory and equipment system"],

["side-view-ink-samurai-duelist",
"side-view ink-brush samurai duelist with stance-based blade combat and a wind-blown particle engine",
"ronin","Ashen Reed Fields","Ghost of Tsushima","Sekiro",
"ink splashes, drifting petals, blade glints, and swaying reeds",
"duel","rival swordsmen to face","stance-based blade combat","winning duels","indigo scarf",
"Make wind direction bend slash arcs and carry ink droplets that mark where cuts land. Keep indoor dojo air still so slashes fly true. Make the wind readable with reed sway, then test the same slash facing upwind and downwind.",
"Let falling leaves pile on the ground and hide light footstep sounds while remaining visible as disturbed drifts. Test ambushes in deep leaf beds and on bare stone without changing the wind and still-air rules.",
"dueling grounds","duel arenas","pilgrimage","a stance and charm loadout"],

["sky-pirate-grappling-hook-platformer",
"3D sky-pirate platformer with grappling-hook traversal and a volumetric wind-current system",
"sky pirate","Stormharbor Rig","The Legend of Zelda: The Wind Waker","Celeste",
"wind streaks, cloud foam, rope sway, and sun shafts through rigging",
"sky trial","sky scavengers to outmaneuver","wind-current grappling","clearing sky trials","brass goggles and red scarf",
"Make storm clouds charge the hook line and release a speed burst on detach. Keep wooden decks insulated so decked landings never shock. Make charged lines crackle visibly, then test the same detach while reeling through cloud and over deck.",
"Let updrafts lift loose cargo and drifting planks. Make the objects ride the existing wind simulation while staying easy to spot and grab. Test pickups inside a thermal and on still decks without changing the charge and insulated-deck rules.",
"skyship wreck","sky islands","ascent","a gadget and rigging workshop"],

["isometric-bone-warden-soulslike",
"isometric soulslike where a bone warden trades guard stamina against a spreading corruption",
"bone warden","Ossuary Depths","Dark Souls","Hades",
"marrow mist, ember cracks in bone, drifting bone dust, and guttering braziers",
"crypt encounter","risen husks to put down","stamina-based bone guard","laying husks to rest","antlered helm",
"Make corruption creep across bone floors and empower husks standing inside it. Keep brazier-lit stone purified so fights near flame stay fair. Make corrupted ground pulse darkly, then test the same pull with the player inside corruption and inside brazier light.",
"Let shattered bone shards lie where they fall and be reforged mid-fight into throwing splinters. Make the shards persist on the ground while staying easy to read and grab. Test drops on corrupted bone and on purified stone without changing the corruption and brazier rules.",
"ossuary","crypt wings","descent","a relic and offering altar"],

["twin-stick-starfish-ranger",
"top-down twin-stick shooter where a starfish ranger swaps tide pools to change ammo",
"starfish ranger","Brineglass Reef","Pikmin","Geometry Wars",
"tide slime, bubble trails, bioluminescent plankton, and rippling shallows",
"reef skirmish","crab raiders to repel","tide-pool ammo swapping","driving off raiders","striped signal shell",
"Make saltwater pools electrify shots that chain between soaked enemies. Keep freshwater pools safe and non-conductive. Make charged pools fizz brightly, then test the same volley while floating in saltwater and in freshwater.",
"Let tides drag shells, pearls, and debris along the reef floor. Make the objects follow the existing tide simulation while remaining easy to identify and collect. Test drops in a riptide lane and in still pools without changing the saltwater and freshwater rules.",
"reef","reef zones","drift","a shell and spine armory"],

["puppet-knight-stageplay-platformer",
"2.5D puppet-knight platformer with string-tension acrobatics across theater stages",
"puppet knight","Candlefoot Stage","Gris","Hollow Knight",
"string physics, footlight glow, paper confetti, and painted backdrops",
"stage act","scene gremlins to swat","string-tension acrobatics","earning applause","painted wooden mask",
"Make standing in a spotlight empower attacks but mark the knight clearly to every enemy. Keep backstage shadow safe for stealth but unable to earn applause. Make lit floorboards glow at the edges, then test the same fight center-spotlight and in the wings.",
"Let cut strings fall and tangle stage machinery into new platforms. Make the fallen strings obey the existing tension simulation while staying easy to read and climb. Test tangles under spotlight and in shadow without changing the spotlight and shadow rules.",
"playhouse","stage acts","tour","a mask and marionette wardrobe"],

["deep-current-diver-explorer",
"first-person diver explorer routing oxygen through living ocean currents",
"diver","Sunken Bell","Subnautica","Outer Wilds",
"current ribbons, plankton bloom, pressure light rays, and swaying kelp",
"dive run","reef eels to evade","oxygen-current routing","charting new depth","yellow brass helmet",
"Make noise propagate through still water and lure eels toward the source. Keep roaring current vents masking so movement inside them stays silent. Make noisy water ring visibly, then test the same sprint inside a vent flow and in still water.",
"Let currents carry oxygen bubbles, shells, and loose gear along the reef. Make the objects drift on the existing current simulation while staying easy to spot and catch. Test pickups inside a vent flow and in still water without changing the noise and masking rules.",
"trench","dive zones","descent","a dive log and gear bench"],

["neon-courier-wall-runner",
"third-person neon courier chaining wall-runs across a rain-slicked megacity",
"courier","Glassrain Ward","Mirror's Edge","Jet Set Radio",
"neon reflections, rain streaks, holographic arrows, and puddle ripples",
"delivery dash","patrol drones to outrun","wall-run momentum chaining","completing deliveries","light-trail jacket",
"Make rainwater pools conduct stun charge from damaged drones across the street. Keep raised dry rails insulated and safe to grind. Make charged puddles flicker cyan, then test the same grind through a flooded alley and along a dry rail.",
"Let storm gusts push loose parcels, flyers, and drones off rhythm. Make the objects react to the existing gust simulation while staying easy to read and intercept. Test pickups in a gust corridor and on calm roofs without changing the flood and dry-rail rules.",
"city","city districts","night shift route","a sneakers and route-mod kit"],

["mech-vs-kaiju-city-brawler",
"arena brawler where a salvage mech wrestles kaiju through destructible city blocks",
"mech pilot","Cinderbay","Pacific Rim","Into the Breach",
"building debris, plasma arcs, smoke columns, and shattering glass",
"city defense","kaiju spawn to topple","building-wreckage throwing","saving civilians","hazard-striped pauldron",
"Make water towers burst and douse overheated mech plating for a cooldown. Keep oil-slicked streets flammable so sparks ignite burning ground. Make scorched plating smoke before it fails, then test the same overheat vent beside a water tower and on an oil slick.",
"Let collapsed facades drop girders and concrete the mech can hurl. Make the wreckage obey the existing destruction physics while staying easy to read and grab. Test throws near water towers and on oil streets without changing the cooling and ignition rules.",
"coastline","city wards","campaign","a chassis and reactor lab"],

["capoeira-rhythm-brawler",
"rhythm brawler where a capoeirista fights inside a drum-driven roda circle",
"capoeirista","Solar Roda","Hi-Fi Rush","Sifu",
"beat rings, kicked dust, crowd glow, and string-light sway",
"roda bout","rival dancers to outplay","beat-locked dodging","winning bouts","green-and-yellow cord belt",
"Make attacks landing on the drumbeat deal bonus ginga damage and extend combos. Keep off-beat strikes weak and briefly staggering. Make the beat pulse readable on the floor ring, then test the same combo played on-beat and fully off-beat.",
"Let the crowd toss flowers, coins, and water gourds into the roda. Make the gifts arc onto the floor while staying easy to see and claim. Test gifts mid-song and during a break without changing the on-beat and off-beat rules.",
"street circuit","street rodas","tournament ladder","cords and instrument charms"],

["dice-gambler-mage-roguelike",
"roguelike where a gambler mage overcharges spells by staking dice",
"gambler mage","Gilded Odds","Hades","Slay the Spire",
"dice sparks, felt-table glow, chip trails, and chandelier flicker",
"gamble bout","debt collectors to outcast","dice-overcharge casting","banishing collectors","loaded-die earring",
"Make chained wins raise the stake multiplier but swell backlash on a bust. Keep banked winnings locked safe once cashed at the altar. Make swollen dice glow hotter each chain, then test the same cast at a triple chain and right after banking.",
"Let felled collectors drop chips and loose dice that tumble to rest. Make the drops settle with real tumble while staying easy to read and claim. Test drops on a hot streak and after banking without changing the stake and banking rules.",
"casino","casino floors","climb","a spell-dice collection"],

["haunted-library-card-battler",
"card battler where an archivist duels margin ghosts among living shelves",
"archivist","Dustwing Stacks","Inscryption","Slay the Spire",
"fluttering pages, candle flicker, ink wisps, and dust in sun shafts",
"reading duel","margin ghosts to exorcise","shelf-order combos","binding ghosts","owl glasses",
"Make candlelit aisles empower verse cards but slowly burn the turn timer. Keep dark aisles safe for planning yet weakening to verse damage. Make lit shelves glow at the trim, then test the same hand inside candlelight and in the dark.",
"Let exorcised ghosts drop loose pages that flutter to the floor. Make the pages drift on the existing air currents while staying easy to spot and shelve. Test drops in candlelight and in the dark without changing the candle and darkness rules.",
"library","library wings","cataloguing","a deck and bookmark binder"],

["pizza-dungeon-chef-roguelike",
"action roguelike where a chef fights dough mimics with heat-zone cooking combat",
"chef","Sourdough Deep","Overcooked","Hades",
"stretching cheese, oven glow, flour dust, and bubbling sauce",
"dinner rush","dough mimics to flatten","heat-zone cooking combat","serving perfect pies","tomato-red bandana",
"Make lava-oven zones cook toppings fast but scorch them if left past the bell. Keep chill-larder alcoves pausing cook timers safely. Make scorching dishes smoke at the rim, then test the same pie in an oven lane and in a larder nook.",
"Let grease slicks spread where fritters fall and slide both chef and mimics. Make the slicks spread on the existing heat simulation while staying easy to read and mop. Test spills in oven lanes and in larder nooks without changing the scorch and chill rules.",
"dungeonendar","dungeon courses","tasting menu","a pantry and knife roll"],

["glass-menagerie-monster-tamer",
"monster tamer raising fragile glass beasts that trade huge power for fragility",
"tamer","Menagerie of Shards","Pokemon","Coromon",
"glass refraction, shard glints, breath fog, and prismatic halos",
"taming rite","wild shards to befriend","glass-fragility trading","completing rites","mirrored whistle",
"Make harmonic chimes calm wild shards and raise tame odds each verse. Keep harsh clangs frightening them into shattering counterattacks. Make calmed shards hum softly, then test the same approach with chimes and with clangs.",
"Let shattered encounters drop prisms that can be fused into new shards. Make the prisms scatter with real bounce while staying easy to see and gather. Test drops after chimes and after clangs without changing the calm and fright rules.",
"menagerie","habitats","expedition","a whistle and terrarium kit"],

["time-loop-village-rpg",
"cozy RPG where a loopkeeper retains memories across a repeating village day",
"loopkeeper","Emberloop Hamlet","Outer Wilds","The Legend of Zelda: Majoras Mask",
"loop embers, bell ripples, deja-vu ghosts, and lantern-lit lanes",
"loop day","loop strays to soothe","loop-memory persistence","soothing strays","bell-brass locket",
"Make the noon bell reset the world but preserve anything rung into memory at a shrine. Keep unshrined progress melting away at the toll. Make remembered objects glint gold, then test the same errand with shrined tools and unshrined tools.",
"Let villager fondness persist faintly across loops once a keepsake is exchanged. Make fondness visible as ribbon colors while staying simple to read. Test bonds with keepsakes and without across two loops without changing the shrine and reset rules.",
"hamlet","village days","seven loops","a memory board and keepsakes"],

["cursed-elevator-tower-ascension",
"ascension roguelike where a bellhop clears tower floors with weight-based lift puzzles",
"bellhop","The Gloaming Lift","Dark Souls","Hades",
"floor-indicator glow, cable sway, mirror fog, and brass polish",
"floor landing","floor wardens to dismiss","elevator-weight puzzles","clearing floors","brass cap badge",
"Make overloading the lift car plunge it a floor but drop heavy wardens off balance. Keep balanced loads granting a smooth express ride upward. Make straining cables groan and spark, then test the same load stacked heavy and balanced light.",
"Let dismissed wardens drop lost luggage that slides when the car jerks. Make the luggage obey the existing car physics while staying easy to spot and claim. Test drops on a plunging car and a smooth car without changing the overload and balance rules.",
"tower","tower floors","ascent","luggage and uniform perks"],

["mushroom-knight-tactics",
"hex-grid tactics where mushroom knights flank through a living mycelium network",
"knight captain","Sporehold","Into the Breach","Fire Emblem",
"spore drift, cap bounce, mycelium veins, and rain drips",
"spore skirmish","blight swarm to encircle","mycelium-link flanking","routing the swarm","spotted cap helm",
"Make linked mycelium tiles share flanking bonuses across the whole web. Keep dry stone tiles unlinked so units there fight alone. Make linked tiles pulse softly, then test the same flank from linked loam and from dry stone.",
"Let felled knights drop spores that seed new links where they land. Make the spores drift on the existing damp-air currents while staying easy to read and harvest. Test drops on linked loam and on dry stone without changing the link and dryness rules.",
"grotto","grotto tiers","descent","a cap and charm barracks"],

["locomotive-deckbuilder-roguelike",
"deckbuilding roguelike where an engineer defends a boiler-driven war train",
"engineer","Emberline Express","Slay the Spire","Frostpunk",
"coal glow, steam bursts, track sparks, and signal-lamp glare",
"rail defense","rail bandits to repel","track-switch routing combat","holding the line","striped conductor cap",
"Make boiler pressure empower attack cards but risk blowout past the red needle. Keep vented steam safe yet discarding a card as the cost. Make the gauge needle tremble near red, then test the same hand fired hot and fully vented.",
"Let wrecked bandits drop coal and spare rivets along the embankment. Make the drops rattle to rest on the existing track physics while staying easy to spot and shovel. Test drops at full pressure and fully vented without changing the pressure and vent rules.",
"railway","rail regions","journey","an engine deck and stoker crew"],

["lantern-bearer-soul-collector",
"atmospheric collector where a lantern bearer guides wisps through consuming dark",
"lantern bearer","Ashen Lantern Road","Hollow Knight","Hades",
"wisp trails, lantern halos, moth swarms, and drinking darkness",
"soul vigil","hollow strays to guide","light-radius soul guiding","guiding strays home","moth-eaten cloak clasp",
"Make lantern light herd wisps toward shrines but burn wick oil while raised high. Keep shuttered low-light safe for oil yet letting wisps wander. Make guided wisps trail gold, then test the same vigil with the lamp high and shuttered.",
"Let stray moths gather fallen wick and dropped embers across the road. Make the pickups glint in the existing light radius while staying easy to see and gather. Test pickups with the lamp high and shuttered without changing the brightness and oil rules.",
"road","road stations","pilgrimage","lantern oils and wick charms"],

["gene-splice-alien-roguelike",
"roguelike where a gene splicer drafts mutations from feral alien splices",
"splicer","Helix Maw","Dead Space","Prey",
"gene goo, membrane pulses, acid hiss, and bioluminescent veins",
"splice trial","feral splices to subdue","gene-draft mutation picks","harvesting helixes","triple-lens visor",
"Make acid blood pools melt armor of anything standing in them. Keep alkaline vents neutralizing acid into safe glass. Make melting pools bubble green, then test the same fight standing in acid and on a vent plate.",
"Let harvested gene samples skitter and must be pinned before bagging. Make the samples squirm with real physics while staying easy to read and pin. Test samples near acid pools and on vent plates without changing the acid and alkaline rules.",
"hive","helix chambers","dive","a gene helix board"],

["cozy-ramen-shop-sim",
"cozy first-person ramen shop sim built around broth-timing rhythm",
"shopkeeper","Steam Alley Stall","Stardew Valley","Diner Dash",
"steam curls, broth shimmer, lantern glow, and noodle pull arcs",
"opening night","hungry regulars to satisfy","broth-timing rhythm","serving happy regulars","flour-dusted headband",
"Make broth served at peak simmer earn perfect-slurp bonuses and tips. Keep scorched pots ruining the batch until scrubbed clean. Make ready broth gleam at the surface, then test the same bowl timed at peak and served scorched.",
"Let dropped toppings and coins scatter where the rush knocks them. Make the items bounce on the existing floor physics while staying easy to spot and grab. Test spills at peak rush and in a calm hour without changing the simmer and scorch rules.",
"alley","shopping streets","food-stall tour","a recipe book and utensils"],

["beeper-valley-beekeeper-sim",
"first-person cozy sim where a beekeeper directs hives with waggle dances",
"beekeeper","Cloverhollow","Stardew Valley","Viva Pinata",
"pollen drift, waggle trails, honey glow, and drowsy bee loops",
"first harvest","mite swarms to smoke out","waggle-dance directing","bringing in harvests","veil-and-straw hat",
"Make flower-scent paths guide foragers home heavy with nectar. Keep smoke-puffed hives calm but drowsy and slow to gather. Make guided bees trail gold, then test the same hive directed by dance and freshly smoked.",
"Let wind scatter petals, wax flakes, and dropped jars across the meadow. Make the items tumble on the existing breeze while staying easy to spot and collect. Test drops on a danced hive and a smoked hive without changing the scent and smoke rules.",
"valley","valley meadows","seasons","hive frames and a smoker kit"],

["floating-island-tea-garden",
"serene gardening sim growing tea across floating islands fed by altitude mist",
"gardener","Mistral Terrace","Stardew Valley","Dorfromantik",
"mist curls, petal fall, kettle steam, and dew on leaves",
"first steeping","leaf aphids to wash off","altitude-mist irrigation","brewing fine teas","wide tea-picker hat",
"Make high-mist beds irrigate leaves passively but chill slow-growing cultivars. Keep sun terraces fast-growing yet quick to scorch. Make thirsty leaves droop visibly, then test the same cultivar in high mist and on a sun terrace.",
"Let gust fronts carry seeds, petals, and snails between islands. Make the drift ride the existing mist currents while staying easy to track and catch. Test drift into high mist and onto sun terraces without changing the mist and scorch rules.",
"garden","sky terraces","tea pilgrimage","a cultivar journal and teaware"],

["dinosaur-ranch-rustler",
"ranch sim where a wrangler lassos dinosaurs with rhythm-based roping",
"rancher","Thundermug Flats","Red Dead Redemption","Stardew Valley",
"dust devils, scale sheen, stampede rumble, and lasso whoosh rings",
"first roundup","rustler drones to rope down","lasso-rhythm wrangling","penning the herd","dino-tooth necklace",
"Make roping on the hoofbeat calm beasts and fill the trust gauge. Keep missed beats spooking them toward a stampede warning. Make calm beasts lower their heads, then test the same catch roped on-beat and fully off-beat.",
"Let startled herds kick up eggs, feed sacks, and tools across the pen. Make the items scatter on the existing dust physics while staying easy to spot and retrieve. Test spills during a calm catch and a spooked stampede without changing the rhythm and spook rules.",
"ranch","ranch ranges","rodeo circuit","a saddle and feed lab"],

["stormborn-viking-saga-roguelike",
"action roguelike where a stormborn viking raids shifting fjords with a rune-carved longship",
"viking","Stormcarved Fjords","God of War","Hades",
"wave spray, rune glow, sail snap, and aurora over snow",
"fjord raid","draugr jarls to dethrone","rune-carved raiding","claiming the fjords","raven-feather cloak clasp",
"Make storm seas empower sail-ramming but swamp the deck past the bale bell. Keep calm fjords swamp-safe yet slow to row. Make swamping decks wash visibly, then test the same raid in storm seas and in a calm fjord.",
"Let dethroned jarls drop runes, amber, and oars in the surf. Make the spoils bob on the existing waves while staying easy to spot and haul. Test spoils in storm seas and in a calm fjord without changing the swamp and slow rules.",
"fjords","fjord reaches","saga","a rune hoard and ship upgrades"],
];
