<?php
// Games 51-75
return [
["ant-colony-pheromone-strategy",
"real-time strategy where a queen's scent-general routes ant legions with a pheromone-trail network",
"scent-general","Underleaf Empire","Pikmin","StarCraft",
"pheromone ribbons, soil crumbs, leaf shadows, and rain drumbeats",
"forage push","termite raiders to repel","pheromone-trail routing","securing the harvest","amber-tipped antennae",
"Make fresh pheromone trails speed legions but evaporate past the fade bell. Keep old trunk trails slow yet permanent once sealed. Make fading trails thin visibly, then test the same push on fresh scent and on sealed trunk.",
"Let raided termites drop chitin, seeds, and dew beads along the trails. Make the drops rest where mandibles drop them while staying easy to spot and haul. Test drops on fresh scent and sealed trunk without changing the fade and permanent rules.",
"colony","nest tiers","swarm seasons","a brood ledger and trail atlas"],
["paper-cut-shadow-puppet-adventure",
"2D shadow-puppet adventure where a cutter folds light with a lantern-mask stealth system",
"cutter","Paper Lantern Revolt","Gris","Mark of the Ninja",
"cut-paper silhouettes, lantern halos, scissor snips, and screen ripples",
"lantern act","paper magistrates to evade","lantern-mask stealth","restoring the play","fox-cut paper mask",
"Make bright screens hide the cutter fully but burn mask oil while exposed. Keep dim screens oil-safe yet half-seen and risky. Make half-seen edges fray visibly, then test the same act under full lantern and in dim glow.",
"Let folded magistrates drop masks, cords, and play scripts backstage. Make the drops lie where they fall while staying easy to spot and pocket. Test drops under full lantern and dim glow without changing the hiding and oil rules.",
"playhouse","lantern acts","tour","a mask chest and cutting kit"],
["volcano-geologist-survival",
"first-person survival where a geologist vents lava tubes with a pressure-bleed drill",
"geologist","Emberthroat","The Long Dark","Subnautica",
"lava glow, ashfall veils, drill sparks, and sulfur steam",
"eruption watch","ash wraiths to outlast","pressure-bleed drilling","sealing the throat","heat-cracked goggles",
"Make vented tubes cool fast but collapse past the brittle tick. Keep unvented tubes stable yet hot enough to scorch. Make brittle rock crackle white, then test the same watch fully vented and sealed hot.",
"Let cooled flows drop obsidian, sulfur, and lost tools on the caldera. Make the finds glint where they cool while staying easy to spot and bag. Test finds vented and sealed hot without changing the collapse and scorch rules.",
"caldera","lava tubes","eruption cycle","a sample case and drill rig"],
["klezmer-golem-rhythm-defense",
"rhythm tower defense where a klezmer conducts golems with a tempo-fiddle baton",
"conductor","Brass Shtetl","Crypt of the NecroDancer","Defense Grid",
"bow strokes, tempo rings, clay dust, and wedding-light strings",
"klezmer night","hollow shells to hold back","tempo-fiddle conducting","holding the shtetl","fiddle-bow baton",
"Make on-tempo orders double golem speed but snap strings past the strain bell. Keep off-tempo orders safe yet marching half-speed. Make straining strings whine visibly, then test the same night conducted on-tempo and fully off-tempo.",
"Let shattered shells drop clay, rosin, and spare strings on the lanes. Make the drops thud where they land while staying easy to spot and gather. Test drops on-tempo and off-tempo without changing the snap and half-speed rules.",
"shtetl","shtetl lanes","wedding season","a golem roster and tune book"],
["sock-puppet-space-opera",
"comedy space opera where a sock captain bluffs warlords with a costume-quick-change teleporter",
"captain","The Laundry Nebula","Portal","Among Us",
"lint nebulas, button glints, dryer-sheet static, and stage-light starfields",
"first contact","warlord armadas to bluff","quick-change disguising","uniting the nebula","mismatched button eyes",
"Make perfect disguises pass checkpoints but unravel past the lint bell if stared at. Keep plain-sock form honest yet barred from war rooms. Make unraveling seams fuzz visibly, then test the same contact disguised and undisguised.",
"Let bluffed warlords drop medals, lint pearls, and spare socks on the bridge. Make the loot tumble in zero-g while staying easy to spot and grab. Test loot disguised and undisguised without changing the unravel and barred rules.",
"nebula","nebula sectors","opera acts","a costume trunk and bluff log"],
["cryptid-photography-horror",
"found-footage horror where a photographer baits cryptids with a flash-and-lure camera",
"photographer","Hollow Pines","Phasmophobia","Pokemon Snap",
"flash blooms, breath fog, branch sway, and red-eye glints",
"night stakeout","ridge cryptids to document","flash-and-lure baiting","completing the roll","taped-up film camera",
"Make flash bursts freeze cryptids for a sharp shot but drain battery and attract the hollow stag. Keep infrared darkroom mode safe yet yielding grainy half-value shots. Make drained batteries blink red, then test the same stakeout flashed bright and shot infrared.",
"Let documented cryptids drop fur, prints, and broken traps in the pines. Make the traces glow under UV while staying easy to spot and bag. Test traces after flash bursts and infrared nights without changing the attract and grainy rules.",
"forest","stakeout sites","expedition","a photo wall and lure kit"],
["ramen-truck-racer",
"arcade racer where a noodle chef drifts a ramen truck with a broth-slosh boost tank",
"chef-driver","Midnight Broth Run","Mario Kart","Crazy Taxi",
"broth slosh, steam plumes, neon signs, and noodle-trail sparks",
"midnight grand prix","rival trucks to outdrift","broth-slosh boosting","taking the grand prix","noodle-bowl helmet",
"Make full broth tanks boost hard but slosh out past the spill bell in hard turns. Keep low tanks grippy yet boostless and slow. Make sloshing tanks rock visibly, then test the same race tanked full and running low.",
"Let outdrifted rivals drop toppings, tickets, and lucky chopsticks on the course. Make the drops skid where they land while staying easy to spot and grab. Test drops tanked full and running low without changing the spill and boostless rules.",
"city","night circuits","season","a broth garage and topping shelf"],
["beacon-tender-coop-climber",
"co-op climber where lighthouse tenders chain lantern relays up a drowned cliff",
"tender","Saltstair","It Takes Two","Celeste",
"lantern chains, wave foam, gull cries, and rope sway",
"cliff ascent","gale shades to outclimb","lantern-relay chaining","lighting the stair","barnacled oil lamp",
"Make chained lanterns share light and warm both climbers on the link. Keep lone lamps warming only the holder while the partner freezes. Make linked flames lean toward each other, then test the same ascent chained and split lone.",
"Let gales scatter oil, wicks, and pitons along the stair. Make the items clatter where they land while staying easy to spot and grab. Test spills chained and split lone without changing the shared and lone rules.",
"cliff","cliff tiers","lighting","a relay map and climbing rack"],
["moss-giant-bonsai-keeper",
"meditative sim where a keeper prunes a walking moss giant with a seasonal-shear calendar",
"keeper","The Ambling Green","Stardew Valley","Shadow of the Colossus",
"petal fall, shear snips, firefly nights, and root rumbles",
"first pruning","rot grubs to pick off","seasonal-shear pruning","raising the green","moss-woven sun hat",
"Make spring shears regrow branches lush but bleed sap past the drip bell. Keep winter shears sap-safe yet slow to regrow. Make bleeding cuts bead visibly, then test the same pruning in spring flush and deep winter.",
"Let pruned branches drop cuttings, grubs, and seed pods on the trail. Make the drops rest where they fall while staying easy to spot and pot. Test drops in spring flush and deep winter without changing the bleed and slow rules.",
"trail","walking provinces","year","a shear roll and growth journal"],
["junkyard-mech-wrestler",
"physics wrestler where a scrapyard mech suplexes rivals with a magnet-grip core",
"wrestler","Rustbelt Rumble","Gang Beasts","Armored Core",
"magnet arcs, scrap showers, oil slicks, and floodlight glare",
"scrap bout","rival rigs to ring-out","magnet-grip throwing","taking the belt","crane-hook shoulder",
"Make magnet grips hold throws tight but overheat past the slag bell. Keep cold grips safe yet easy to break. Make overheating cores glow at the seams, then test the same bout gripped hot and stone cold.",
"Let rung-out rigs shed plates, coils, and lucky bolts ringside. Make the debris clang where it lands while staying easy to spot and salvage. Test debris from hot bouts and cold bouts without changing the overheat and break rules.",
"yard","scrap rings","circuit","a magnet lab and scrap ledger"],
["opera-ghost-stagehand",
"stealth adventure where a stagehand haunts an opera with a trapdoor-and-chandelier rig",
"stagehand","The Gilded Fall","Hitman","Luigis Mansion",
"chandelier sway, curtain dust, footlight pools, and score-page flutters",
"opening night","critic wraiths to drop","trapdoor-and-chandelier rigging","bringing down the house","paint-splattered cap",
"Make chandelier drops silence whole rows but swing wild past the sway bell. Keep trapdoor tricks quiet yet single-target only. Make swaying chains groan visibly, then test the same night swung wide and trapped quiet.",
"Let dropped wraiths leave tickets, roses, and lost scores in the aisles. Make the keepsakes lie where they fall while staying easy to spot and collect. Test keepsakes swung wide and trapped quiet without changing the silence and single-target rules.",
"opera","opera nights","season","a rigging plot and prop loft"],
["tea-dragon-pet-sim",
"virtual-pet sim where a keeper steeps moods for a tea dragon with a kettle-temperament bar",
"keeper","Steeppeak","Tamagotchi","Viva Pinata",
"steam curls, scale shimmer, bubble chirps, and petal rain",
"first steeping","tantrum chills to soothe","kettle-temperament steeping","raising a tea master","tea-leaf scarf",
"Make peak-steeped tea excite the dragon into tricks but scald past the steam bell. Keep lukewarm tea calm yet trickless and drowsy. Make scalded snouts puff visibly, then test the same day steeped peak and served lukewarm.",
"Let trick shows scatter scales, coins, and tea cakes on the mats. Make the gifts rest where they land while staying easy to spot and pocket. Test gifts steeped peak and served lukewarm without changing the scald and drowsy rules.",
"peak","tea rooms","festival year","a steep log and treat shelf"],
["graffiti-golem-street-battler",
"street battler where a writer tags golems awake with a spray-pressure crew",
"writer","Chroma Blocks","Jet Set Radio","Streets of Rage",
"spray cones, paint drips, siren sweeps, and roller rumble",
"block jam","buff-squad cleaners to outpaint","spray-pressure tagging","holding the blocks","respirator mask and paint-splattered hoodie",
"Make high-pressure tags summon golems fast but drip past the run bell. Keep low-pressure tags crisp yet slow to wake. Make running paint streak visibly, then test the same jam sprayed high and feathered low.",
"Let buffed walls drop caps, cans, and sketchbooks in the alley. Make the drops clatter where they fall while staying easy to spot and grab. Test drops sprayed high and feathered low without changing the drip and slow rules.",
"district","painted blocks","crew season","a cap wall and blackbook"],
["quilt-witch-crafting-rpg",
"cozy crafting RPG where a quilt witch stitches spells with a patchwork-grid loom",
"witch","Patchlight Hollow","Stardew Valley","Gris",
"patchwork glow, thread trails, button glints, and hearth embers",
"patch quest","unraveled strays to mend","patchwork-grid stitching","quilt the dawn blanket","thimble crown",
"Make moonlit stitches hold strong but fray past the pull bell if rushed. Keep hearthside stitches slow yet unfraying. Make fraying seams buzz visibly, then test the same quest stitched moonlit and hearthside.",
"Let mended strays leave buttons, scraps, and thimbles on the quilt. Make the gifts rest where they land while staying easy to spot and pocket. Test gifts stitched moonlit and hearthside without changing the fray and slow rules.",
"hollow","quilt districts","year","a button jar and loom chart"],
["storm-shepherd-flock-flyer",
"flock flyer where a shepherd steers storm geese with a wind-whistle wedge",
"shepherd","Galebrood","Star Fox","Journey",
"wingtip vapor, whistle rings, rain veils, and lightning forks",
"migration leg","sky poachers to outfly","wind-whistle wedge steering","bringing the flock home","storm-grey shepherd coat",
"Make tight wedges fly fast but tire wings past the pant bell. Keep loose wedges rested yet slow and scattered. Make panting wings droop visibly, then test the same leg flown tight and drifting loose.",
"Let scattered storms drop feathers, sky-apples, and lost bells along the route. Make the falls drift on the existing wind while staying easy to spot and catch. Test falls flown tight and drifting loose without changing the tire and scatter rules.",
"skyway","migration legs","season","a whistle set and flock roll"],
["mushroom-subway-builder",
"transit builder where a mole conductor links mushroom stations with a spore-timetable grid",
"conductor","Myceline","Mini Metro","Cities: Skylines",
"spore puffs, tunnel drips, lamp pools, and train rumble",
"rush hour","blight jams to clear","spore-timetable routing","uniting the myceline","brass conductor whistle",
"Make express spores skip stops fast but jam past the clog bell. Keep local spores jam-safe yet slow at every cap. Make clogging tunnels bulge visibly, then test the same hour run express and all-local.",
"Let cleared jams drop spores, tickets, and lost umbrellas on platforms. Make the finds rest where sweepers leave them while staying easy to spot and claim. Test finds run express and all-local without changing the jam and slow rules.",
"network","tunnel boroughs","timetable year","a timetable board and cap collection"],
["bone-choir-rhythm-horror",
"rhythm horror where a chorister keeps a bone choir singing with a breath-lantern meter",
"chorister","Ossuary Hymn","Crypt of the NecroDancer","Amnesia",
"choir breath rings, lantern sway, bone chimes, and dust falls",
"midnight requiem","silent ones to outsong","breath-lantern singing","finishing the requiem","choir robe with bone clasps",
"Make full-breath verses banish the silent but gutter the lantern past the dim bell. Keep shallow breaths lamp-safe yet barely holding them back. Make guttering flames shrink visibly, then test the same requiem sung full and breathed shallow.",
"Let banished silent ones drop teeth, hymn sheets, and wax on the steps. Make the relics rest where they fall while staying easy to spot and gather. Test relics sung full and breathed shallow without changing the gutter and weak rules.",
"ossuary","choir nights","requiem","a hymnal and lantern oils"],
["pickle-knight-tactics",
"comedy tactics where a pickle knight brines battlefields with a vinegar-mist catapult",
"knight","Brinehold","Into the Breach","Worms",
"vinegar mist, crunch shards, jar glints, and dill drift",
"brine skirmish","bland wraiths to season","vinegar-mist zoning","taking Brinehold","dill-plume helm",
"Make vinegar zones melt bland armor fast but pickle allies past the pucker bell. Keep fresh zones safe yet flavorless and weak. Make puckering allies wince visibly, then test the same skirmish fought brined and fresh.",
"Let seasoned wraiths drop lids, spices, and recipe cards on the grid. Make the drops rest where they land while staying easy to spot and collect. Test drops fought brined and fresh without changing the pucker and weak rules.",
"keep","brine wards","season","a spice rack and jar armory"],
["aurora-cartographer-explorer",
"sky explorer where a cartographer inks aurora maps with a starfix-sight balloon",
"cartographer","Vellum Lights","Outer Wilds","Abzu",
"aurora ribbons, ink drifts, balloon creaks, and star pricks",
"chart flight","storm cells to outdrift","starfix-sight mapping","inking the lights","star-chart satchel",
"Make aurora-bright legs ink fast but scramble the compass past the spin bell. Keep dark legs compass-true yet inking slowly. Make spinning needles whirl visibly, then test the same flight aurora-bright and star-dark.",
"Let mapped storms drop lenses, charts, and ballast sand on the gondola. Make the finds slide where gusts leave them while staying easy to spot and stow. Test finds aurora-bright and star-dark without changing the scramble and slow rules.",
"lights","sky reaches","expedition","a map case and lens kit"],
["comet-blacksmith-action",
"action forge where a blacksmith hammers comet iron with an orbit-strike anvil",
"blacksmith","Starfall Forge","God of War","Hades",
"comet streaks, anvil rings, slag sparks, and forge auroras",
"starfall rush","rust husks to hammer","orbit-strike forging","forging the starblade","star-iron apron",
"Make comet-hot ingots forge fast but burn grips past the blister bell. Keep cold ingots grip-safe yet brittle to crack. Make cracking ingots ping visibly, then test the same rush hammered hot and cold.",
"Let shattered husks drop shards, coal, and star sand by the anvil. Make the drops bounce where they land while staying easy to spot and quench. Test drops hammered hot and cold without changing the burn and brittle rules.",
"forge","forge vales","meteor season","a hammer wall and quench barrels"],
["sourdough-dragon-keeper",
"bakery battler where a baker duels with a sourdough starter dragon and a proof-heat oven",
"baker","Crumbwing Bakery","Pokemon","Overcooked",
"flour dust, proof bubbles, oven glow, and wing-flap gusts",
"bake-off bout","health-inspector shades to outbake","proof-heat oven dueling","winning the blue ribbon","flour-dusted dragon-scale apron",
"Make long-proofed loaves hit hard but overproof past the sour bell. Keep quick loaves safe yet dealing chip damage. Make overproofed dough sag visibly, then test the same bout fought long-proofed and quick-baked.",
"Let outbaked shades drop starters, peels, and ribbons on the tiles. Make the drops rest where they land while staying easy to spot and claim. Test drops long-proofed and quick-baked without changing the sour and chip rules.",
"bakery","baking districts","fair season","a starter shelf and peel rack"],
["ferret-postman-stealth",
"stealth courier where a ferret postman slips parcels past hawk patrols with a scent-pouch system",
"postman","Thistledown Route","Hitman","Untitled Goose Game",
"tube sway, feather shadows, bell jingles, and grass rustle",
"mail run","hawk patrols to slip past","scent-pouch sneaking","delivering every parcel","satchel with brass buckle",
"Make rain-washed runs scentless but slow through mud past the squelch bell. Keep dry runs fast yet scent-marked for hawks. Make marked trails shimmer visibly, then test the same run washed rainy and run dry.",
"Let startled senders drop stamps, twine, and biscuits along the route. Make the mail rest where it falls while staying easy to spot and post. Test mail washed rainy and run dry without changing the slow and marked rules.",
"route","delivery wards","postal year","a stamp album and scent kit"],
["ice-sculptor-duelist",
"duelist where an ice sculptor parries with a freeze-frame chisel and a meltwater stage",
"sculptor","Frostbite Gallery","Sekiro","Sifu",
"chisel chips, melt streams, gallery spots, and breath fog",
"gallery duel","rival sculptors to outcarve","freeze-frame parrying","taking the exhibition","frost-blue sculptor smock",
"Make frozen stages parry clean but crack past the fracture bell. Keep meltwater stages crack-safe yet slippery to stance. Make cracking ice spider visibly, then test the same duel fought frozen and half-melted.",
"Let outcarved rivals shed chisels, pigments, and ribbons on the ice. Make the tools skid where they fall while staying easy to spot and claim. Test tools fought frozen and half-melted without changing the crack and slippery rules.",
"gallery","gallery halls","exhibition","a chisel roll and pigment shelf"],
["junk-dragon-hoarder-sim",
"hoard sim where a junk dragon values trash with a shine-appraisal sneeze",
"dragon","Glimmerheap","Viva Pinata","Stardew Valley",
"shine glints, coin avalanches, sneeze embers, and dust motes",
"hoard day","knight collectors to sneeze off","shine-appraisal sneezing","raising the glimmerheap","bottlecap scale polish",
"Make sneeze appraisals price piles fast but scatter them past the gust bell. Keep paw-sorted piles tidy yet slow to value. Make scattering coins roll visibly, then test the same day sneezed loud and paw-sorted.",
"Let sneezed knights drop shields, deeds, and lunch pails on the heap. Make the loot half-bury where it lands while staying easy to spot and drag in. Test loot sneezed loud and paw-sorted without changing the scatter and slow rules.",
"heap","hoard warrens","hoard years","a shine ledger and sneeze chart"],
["midnight-diner-detective-rpg",
"detective RPG where a line cook solves cases with an order-ticket deduction grill",
"cook","The Griddle File","Disco Elysium","Diner Dash",
"grill sizzle, ticket rails, neon through blinds, and coffee steam",
"night shift","lying regulars to serve-justice","order-ticket deduction","closing every case","grease-spotted name tag",
"Make rush-hour interrogations crack suspects fast but burn orders past the char bell. Keep slow-hour talks burn-safe yet yielding thin leads. Make charring tickets smoke visibly, then test the same shift rushed and slow.",
"Let cracked suspects leave keys, photos, and unpaid tabs on the counter. Make the evidence sit where left while staying easy to read and file. Test evidence rushed and slow without changing the crack and thin rules.",
"diner","diner nights","casebook","a ticket rail and evidence drawer"],
];
